import { useTranslation } from 'react-i18next';
import { ArrowRight } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@shared/ui/card';
import { Button } from '@shared/ui/button';
import { StatusChip } from '@shared/ui/status-chip';
import { Empty, EmptyContent, EmptyDescription, EmptyMedia, EmptyTitle } from '@shared/ui/empty';
import type { CompetitorOpportunity } from '../../types';
import { competitorConfidenceTone } from './status';

interface OpportunityListProps {
  opportunities: CompetitorOpportunity[];
  /** Deep-link into a NEW content analysis prefilled with the run's owned URL. */
  onStartAnalysis: () => void;
}

/**
 * Machine-generated content opportunities with their evidence source ids +
 * confidence. Labels are plain-language and generated by the deterministic
 * delta pipeline (never competitor prose) — still rendered as React text nodes.
 */
export function OpportunityList({ opportunities, onStartAnalysis }: OpportunityListProps) {
  const { t } = useTranslation('contentIntelligence');
  return (
    <Card data-testid="competitor-opportunities">
      <CardHeader className="flex flex-row items-start justify-between gap-4">
        <div className="flex flex-col gap-1.5">
          <CardTitle>{t('competitorContent.opportunities.title')}</CardTitle>
          <CardDescription>{t('competitorContent.opportunities.description')}</CardDescription>
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={onStartAnalysis}
          data-testid="competitor-start-analysis"
        >
          {t('competitorContent.opportunities.startAnalysis')}
          <ArrowRight aria-hidden="true" className="ms-2 size-4 rtl:rotate-180" />
        </Button>
      </CardHeader>
      <CardContent>
        {opportunities.length === 0 ? (
          <Empty data-testid="competitor-opportunities-empty">
            <EmptyMedia />
            <EmptyContent>
              <EmptyTitle>{t('competitorContent.opportunities.empty')}</EmptyTitle>
              <EmptyDescription>
                {t('competitorContent.opportunities.emptyHint')}
              </EmptyDescription>
            </EmptyContent>
          </Empty>
        ) : (
          <ul className="flex flex-col gap-3">
            {opportunities.map((opp) => (
              <li
                key={opp.id}
                className="border-border flex flex-col gap-2 rounded-md border p-3"
                data-testid={`competitor-opportunity-${opp.id}`}
              >
                <div className="flex flex-wrap items-center gap-2">
                  <StatusChip tone="muted">
                    {t(`competitorContent.opportunities.kinds.${opp.kind}`)}
                  </StatusChip>
                  <span className="font-medium">{opp.label}</span>
                  <StatusChip tone={competitorConfidenceTone(opp.confidence)}>
                    {t('competitorContent.findings.confidence', {
                      value: t(`competitorContent.confidence.${opp.confidence}`),
                    })}
                  </StatusChip>
                </div>
                <p className="text-muted-foreground text-xs">
                  {t('competitorContent.findings.evidence', {
                    count: opp.evidenceSourceIds.length,
                  })}
                </p>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}
