export const COMPETITOR_PORTFOLIO_MAX_COMPETITORS = 10;
export const COMPETITOR_CONTENT_PAGES_PER_RUN = 15;
export const COMPETITOR_CONTENT_SNIPPET_MAX_CHARS = 500;
export const COMPETITOR_CONTENT_NGRAM_SIZE = 5;
export const COMPETITOR_CONTENT_NGRAM_SIMILARITY_THRESHOLD = 0.4;
export const CONTENT_MONITOR_ACTIVE_LIMIT = 5;
