ALTER TABLE "billing_checkout_intents" DROP CONSTRAINT "billing_checkout_intents_custom_linkage_check";--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "amount_cents" bigint;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "currency" text;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "interval" text;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "pricing_version_id" text;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "pricing_checksum" text;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "canonical_hash" text;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "provider_price_id" text;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "provider_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD COLUMN "attempt_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD CONSTRAINT "billing_checkout_intents_provider_expiry_check" CHECK ("billing_checkout_intents"."provider_expires_at" is null or "billing_checkout_intents"."provider_expires_at" > "billing_checkout_intents"."created_at");--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD CONSTRAINT "billing_checkout_intents_attempt_count_check" CHECK ("billing_checkout_intents"."attempt_count" >= 0);--> statement-breakpoint
ALTER TABLE "billing_checkout_intents" ADD CONSTRAINT "billing_checkout_intents_custom_linkage_check" CHECK (("billing_checkout_intents"."kind" = 'custom' and "billing_checkout_intents"."plan_source" = 'custom' and "billing_checkout_intents"."custom_quote_id" is not null and "billing_checkout_intents"."product_id" is not null and "billing_checkout_intents"."amount_cents" is not null and "billing_checkout_intents"."amount_cents" > 0 and "billing_checkout_intents"."currency" is not null and "billing_checkout_intents"."interval" in ('monthly', 'yearly') and "billing_checkout_intents"."pricing_version_id" is not null and "billing_checkout_intents"."pricing_checksum" ~ '^[0-9a-f]{64}$' and "billing_checkout_intents"."canonical_hash" ~ '^[0-9a-f]{64}$') or ("billing_checkout_intents"."kind" <> 'custom' and "billing_checkout_intents"."custom_quote_id" is null and "billing_checkout_intents"."custom_contract_id" is null and "billing_checkout_intents"."custom_revision_id" is null and "billing_checkout_intents"."amount_cents" is null and "billing_checkout_intents"."currency" is null and "billing_checkout_intents"."interval" is null and "billing_checkout_intents"."pricing_version_id" is null and "billing_checkout_intents"."pricing_checksum" is null and "billing_checkout_intents"."canonical_hash" is null and "billing_checkout_intents"."provider_price_id" is null and "billing_checkout_intents"."provider_expires_at" is null));